#!/bin/bash
# SCRIPT DE INICIO RÁPIDO - Casa Rural Cádiz
# Este archivo documenta los comandos para empezar rápidamente

echo "🚀 CASA RURAL DE PRUEBAS - GUÍA DE INICIO"
echo "=========================================="
echo ""
echo "📁 Ubicación: /home/macky/codex-web/Actividad-CODEX-y-WEB"
echo ""
echo "✅ ARCHIVOS CREADOS:"
echo "  - index.html (página principal)"
echo "  - style.css (estilos responsivos)"
echo "  - politica-privacidad.md"
echo "  - aviso-legal.md"
echo "  - cookies.md"
echo "  - README.md (documentación completa)"
echo "  - PUBLICAR.md (guía GitHub Pages)"
echo "  - CUSTOMIZAR.md (personalización)"
echo "  - TESTING.md (validación)"
echo "  - INICIO_RAPIDO.md (resumen)"
echo ""
echo "🎯 PRÓXIMOS PASOS:"
echo ""
echo "1️⃣ PERSONALIZAR (Opcional pero recomendado)"
echo "   - Edita index.html"
echo "   - Cambia: nombre, email, teléfono, WhatsApp"
echo "   - Ref: Ver archivo CUSTOMIZAR.md"
echo ""
echo "2️⃣ PUBLICAR EN GITHUB PAGES"
echo "   $ cd /home/macky/codex-web/Actividad-CODEX-y-WEB"
echo "   $ git init"
echo "   $ git add ."
echo "   $ git commit -m 'Casa Rural website'"
echo "   $ git remote add origin https://github.com/TU_USUARIO/casa-rural-cadiz.git"
echo "   $ git branch -M main"
echo "   $ git push -u origin main"
echo ""
echo "3️⃣ ACTIVAR GITHUB PAGES"
echo "   - Ve a Settings > Pages"
echo "   - Branch: main"
echo "   - Folder: / (root)"
echo "   - Espera 2-3 minutos"
echo ""
echo "4️⃣ ¡LISTO!"
echo "   - URL: https://TU_USUARIO.github.io/casa-rural-cadiz/"
echo ""
echo "📚 DOCUMENTACIÓN:"
echo "   📖 README.md - Guía técnica completa"
echo "   📖 PUBLICAR.md - 5 pasos para GitHub Pages"
echo "   📖 CUSTOMIZAR.md - Personalización"
echo "   📖 TESTING.md - Validación"
echo "   📖 VISUAL.txt - Resumen visual"
echo ""
echo "🌐 ENLACES ÚTILES:"
echo "   GitHub Pages: https://pages.github.com"
echo "   Unsplash: https://unsplash.com"
echo "   W3C HTML: https://validator.w3.org"
echo "   W3C CSS: https://jigsaw.w3.org/css-validator"
echo ""
echo "✨ ¡Tu web está lista para el mundo! 🌍"
echo ""
